name = "Mirage"
uuid = "e54eaeca-a684-404c-9867-c26beaca1479"
version = "0.1.0"
authors = ["groverburger <19754251+groverburger@users.noreply.github.com>"]

[deps]
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GLFW = "f7f18e0c-5ee9-5ccd-a5bf-e8befd85ed98"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
ModernGL = "66fc600b-dfda-50eb-8b99-91cfa97b1301"

[compat]
FileIO = "1.17.0"
ImageIO = "0.6.9"
Images = "0.26.2"
